package com.miku.ray.handler

import com.miku.ray.AppConfig
import kotlinx.coroutines.channels.BufferOverflow
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow

data class UiCustomizationState(
    val appTheme: String,
    val useCustomColor: Boolean,
    val customColor: Int,
    val dynamicColor: Boolean,
    val dynamicColorBanner: Boolean,
    val disableHomeBanner: Boolean,
    val trueBlack: Boolean,
    val enableBlur: Boolean,
    val useSystemBlur: Boolean,
    val blurBottomStatus: Boolean,
    val language: String,
    val nightTheme: String,
    val iconShape: String,
    val arrowShape: String,
    val appFont: String,
    val useCustomFont: Boolean,
    val toolbarCenterSubtitleMode: Boolean,
    val showIspInfo: Boolean,
    val showSplash: Boolean,
    val groupAllTabIcon: String,
    val selectedBannerStyleEnabled: Boolean,
    val weatherUnit: String,
    val weatherLocation: String,
    val trafficEnabled: Boolean,
    val disableSensorText: Boolean,
    val networkSecurityEnabled: Boolean,
    val confirmRemove: Boolean,
    val startScanImmediate: Boolean,
    val groupAllDisplay: Boolean,
    val speedEnabled: Boolean,
    val hideDirectTrafficNotification: Boolean,
    val showGroupNameNotification: Boolean,
    val customAppName: String,
    val enableParticlesSheet: Boolean,
    val customProfileName: String,
    val profileBannerUri: String,
    val profileBannerShape: String,
    val soundOnConnect: Boolean,
    val customSheetBannerUri: String,
    val sheetBannerDim: Int,
    val particlesFrameDelay: Float,
    val particlesLineLength: Float,
    val particlesLineThickness: Float,
    val particlesRadiusMax: Float,
    val particlesRadiusMin: Float,
    val particlesDensity: Float,
    val particlesSpeedFactor: Float,
    val bannerCharacterWidth: Float,
    val bannerCharacterHeight: Float,
    val bannerCharacterMarginTop: Float,
    val bannerCharacterMarginBottom: Float,
    val bannerCharacterMarginEnd: Float,
    val customDpi: Int,
    val appFontSize: Float,
    val quickActions: Boolean,
    val snowflakesEnabled: Boolean,
    val snowflakesSpeed: Float,
    val snowflakesCount: Int,
    val snowflakesSize: Float,
    val snowflakesOpacity: Float,
    val snowflakesWind: Float,
    val snowflakesLife: Float,
    val showRealtimeTrafficIp: Boolean,
    val homeBannerDisabled: Boolean,
    val homeBannerUri: String,
    val homeBannerHeight: Int,
    val headerTopRowPadding: Int,
    val tabBadgeLimit: String,
    val fabExtended: Boolean,
    val toolbarCenterSubtitle: Boolean,
    val searchBarChip: String,
    val searchChipGradient: Boolean,
    val doubleColumnDisplay: Boolean,
    val hideScrollButtons: Boolean,
    val compactListActions: Boolean,
    val indicatorStyle: String,
    val categoryStyle: String,
    val selectedBannerEnabled: Boolean,
    val selectedBannerUri: String,
    val selectedBannerDim: Int,
    val blurEnabled: Boolean,
    val blurRadius: Int,
    val blurRounds: Int,
    val blurBottomBlobAnimation: Boolean,
    val blurBottomRadius: Float,
    val blurBottomAlpha: Int
)

object UiCustomizationStateStore {
    private val _state = MutableStateFlow(readState())
    val state: StateFlow<UiCustomizationState> = _state.asStateFlow()

    private val _events = MutableSharedFlow<Unit>(
        extraBufferCapacity = 1,
        onBufferOverflow = BufferOverflow.DROP_OLDEST
    )
    val events: SharedFlow<Unit> = _events.asSharedFlow()

    fun refresh() {
        _state.value = readState()
        _events.tryEmit(Unit)
    }

    private fun readState() = UiCustomizationState(
        appTheme = string(AppConfig.PREF_APP_THEME, "8"),
        useCustomColor = bool(AppConfig.PREF_USE_CUSTOM_COLOR),
        customColor = int(AppConfig.PREF_CUSTOM_COLOR, 0),
        dynamicColor = bool(AppConfig.PREF_DYNAMIC_COLOR),
        dynamicColorBanner = bool(AppConfig.PREF_DYNAMIC_COLOR_BANNER),
        disableHomeBanner = bool(AppConfig.PREF_DISABLE_HOME_BANNER),
        trueBlack = bool(AppConfig.PREF_TRUE_BLACK),
        enableBlur = bool(AppConfig.PREF_ENABLE_BLUR),
        useSystemBlur = bool(AppConfig.PREF_USE_SYSTEM_BLUR),
        blurBottomStatus = bool(AppConfig.PREF_BLUR_BOTTOM_STATUS),
        language = string(AppConfig.PREF_LANGUAGE),
        nightTheme = string(AppConfig.PREF_UI_MODE_NIGHT, "0"),
        iconShape = string(AppConfig.PREF_ICON_SHAPE, "uwu_shape_cookie"),
        arrowShape = string(AppConfig.PREF_ARROW_SHAPE, "uwu_shape_circle"),
        appFont = string(AppConfig.PREF_APP_FONT, "default"),
        useCustomFont = bool(AppConfig.PREF_APP_FONT_USE_CUSTOM),
        toolbarCenterSubtitleMode = bool(AppConfig.PREF_TOOLBAR_CENTER_SUBTITLE_MODE),
        showIspInfo = bool(AppConfig.PREF_SHOW_ISP_INFO),
        showSplash = bool(AppConfig.PREF_SHOW_SPLASH),
        groupAllTabIcon = string(AppConfig.PREF_GROUP_ALL_TAB_ICON),
        selectedBannerStyleEnabled = bool(AppConfig.PREF_SELECTED_BANNER_STYLE_ENABLED),
        weatherUnit = string(AppConfig.PREF_WEATHER_USE_CELSIUS),
        weatherLocation = string(AppConfig.PREF_WEATHER_CUSTOM_LOCATION),
        trafficEnabled = bool(AppConfig.PREF_TRAFFIC_ENABLED),
        disableSensorText = bool(AppConfig.PREF_DISABLE_SENSOR_TEXT),
        networkSecurityEnabled = bool(AppConfig.PREF_NETWORK_SECURITY_ENABLED),
        confirmRemove = bool(AppConfig.PREF_CONFIRM_REMOVE, true),
        startScanImmediate = bool(AppConfig.PREF_START_SCAN_IMMEDIATE),
        groupAllDisplay = bool(AppConfig.PREF_GROUP_ALL_DISPLAY),
        speedEnabled = bool(AppConfig.PREF_SPEED_ENABLED),
        hideDirectTrafficNotification = bool(AppConfig.PREF_HIDE_DIRECT_TRAFFIC_NOTIFICATION),
        showGroupNameNotification = bool(AppConfig.PREF_SHOW_GROUP_NAME_NOTIFICATION),
        customAppName = string(AppConfig.PREF_CUSTOM_APP_NAME, "default"),
        enableParticlesSheet = bool(AppConfig.PREF_ENABLE_PARTICLES_SHEET),
        customProfileName = string(AppConfig.PREF_CUSTOM_PROFILE_NAME),
        profileBannerUri = string(AppConfig.PREF_PROFILE_BANNER_URI),
        profileBannerShape = string(AppConfig.PREF_PROFILE_BANNER_SHAPE, AppConfig.PREF_PROFILE_BANNER_SHAPE_DEFAULT),
        soundOnConnect = bool(AppConfig.PREF_SOUND_ON_CONNECT, true),
        customSheetBannerUri = string(AppConfig.PREF_CUSTOM_SHEET_BANNER_URI),
        sheetBannerDim = int(AppConfig.PREF_SHEET_BANNER_DIM, AppConfig.SHEET_BANNER_DIM_DEFAULT),
        particlesFrameDelay = float(AppConfig.PREF_PARTICLES_FRAME_DELAY, AppConfig.PARTICLES_FRAME_DELAY_DEFAULT),
        particlesLineLength = float(AppConfig.PREF_PARTICLES_LINE_LENGTH, AppConfig.PARTICLES_LINE_LENGTH_DEFAULT),
        particlesLineThickness = float(AppConfig.PREF_PARTICLES_LINE_THICKNESS, AppConfig.PARTICLES_LINE_THICKNESS_DEFAULT),
        particlesRadiusMax = float(AppConfig.PREF_PARTICLES_RADIUS_MAX, AppConfig.PARTICLES_RADIUS_MAX_DEFAULT),
        particlesRadiusMin = float(AppConfig.PREF_PARTICLES_RADIUS_MIN, AppConfig.PARTICLES_RADIUS_MIN_DEFAULT),
        particlesDensity = float(AppConfig.PREF_PARTICLES_DENSITY, AppConfig.PARTICLES_DENSITY_DEFAULT),
        particlesSpeedFactor = float(AppConfig.PREF_PARTICLES_SPEED_FACTOR, AppConfig.PARTICLES_SPEED_FACTOR_DEFAULT),
        bannerCharacterWidth = float(AppConfig.PREF_BANNER_CHARACTER_WIDTH, AppConfig.BANNER_CHARACTER_WIDTH_DEFAULT),
        bannerCharacterHeight = float(AppConfig.PREF_BANNER_CHARACTER_HEIGHT, AppConfig.BANNER_CHARACTER_HEIGHT_DEFAULT),
        bannerCharacterMarginTop = float(AppConfig.PREF_BANNER_CHARACTER_MARGIN_TOP, AppConfig.BANNER_CHARACTER_MARGIN_TOP_DEFAULT),
        bannerCharacterMarginBottom = float(AppConfig.PREF_BANNER_CHARACTER_MARGIN_BOTTOM, AppConfig.BANNER_CHARACTER_MARGIN_BOTTOM_DEFAULT),
        bannerCharacterMarginEnd = float(AppConfig.PREF_BANNER_CHARACTER_MARGIN_END, AppConfig.BANNER_CHARACTER_MARGIN_END_DEFAULT),
        customDpi = int(AppConfig.PREF_CUSTOM_DPI, 0),
        appFontSize = float(AppConfig.PREF_APP_FONT_SIZE, AppConfig.FONT_SIZE_DEFAULT),
        quickActions = bool(AppConfig.PREF_SHOW_QUICK_ACTIONS),
        snowflakesEnabled = bool(AppConfig.PREF_ENABLE_SNOWFLAKES),
        snowflakesSpeed = float(AppConfig.PREF_SNOWFLAKES_SPEED, AppConfig.SNOWFLAKES_SPEED_DEFAULT),
        snowflakesCount = int(AppConfig.PREF_SNOWFLAKES_COUNT, AppConfig.SNOWFLAKES_COUNT_DEFAULT),
        snowflakesSize = float(AppConfig.PREF_SNOWFLAKES_SIZE, AppConfig.SNOWFLAKES_SIZE_DEFAULT),
        snowflakesOpacity = float(AppConfig.PREF_SNOWFLAKES_OPACITY, AppConfig.SNOWFLAKES_OPACITY_DEFAULT),
        snowflakesWind = float(AppConfig.PREF_SNOWFLAKES_WIND, AppConfig.SNOWFLAKES_WIND_DEFAULT),
        snowflakesLife = float(AppConfig.PREF_SNOWFLAKES_LIFE, AppConfig.SNOWFLAKES_LIFE_DEFAULT),
        showRealtimeTrafficIp = bool(AppConfig.PREF_SHOW_REALTIME_TRAFFIC_IP),
        homeBannerDisabled = bool(AppConfig.PREF_DISABLE_HOME_BANNER),
        homeBannerUri = string(AppConfig.PREF_CUSTOM_HOME_BANNER_URI),
        homeBannerHeight = int(AppConfig.PREF_HOME_BANNER_HEIGHT, AppConfig.HOME_BANNER_HEIGHT_DEFAULT),
        headerTopRowPadding = int(AppConfig.PREF_HEADER_TOP_ROW_PADDING, AppConfig.HEADER_TOP_ROW_PADDING_DEFAULT),
        tabBadgeLimit = string(AppConfig.PREF_TAB_BADGE_LIMIT, "0"),
        fabExtended = bool(AppConfig.PREF_FAB_EXTENDED),
        toolbarCenterSubtitle = bool(AppConfig.PREF_TOOLBAR_CENTER_SUBTITLE_MODE),
        searchBarChip = string(AppConfig.PREF_SEARCH_BAR_CHIP, "disabled"),
        searchChipGradient = bool(AppConfig.PREF_SEARCH_CHIP_GRADIENT),
        doubleColumnDisplay = bool(AppConfig.PREF_DOUBLE_COLUMN_DISPLAY),
        hideScrollButtons = bool(AppConfig.PREF_HIDE_SCROLL_BUTTONS),
        compactListActions = bool(AppConfig.PREF_COMPACT_LIST_ACTIONS),
        indicatorStyle = string(AppConfig.PREF_INDICATOR_STYLE, "STYLE_0"),
        categoryStyle = string(AppConfig.PREF_CATEGORY_STYLE, "gradient"),
        selectedBannerEnabled = bool(AppConfig.PREF_SELECTED_BANNER_STYLE_ENABLED),
        selectedBannerUri = string(AppConfig.PREF_SELECTED_BANNER_URI),
        selectedBannerDim = int(AppConfig.PREF_SELECTED_BANNER_DIM, AppConfig.SELECTED_BANNER_DIM_DEFAULT),
        blurEnabled = bool(AppConfig.PREF_ENABLE_BLUR),
        blurRadius = int(AppConfig.PREF_BLUR_RADIUS, AppConfig.DEFAULT_BLUR_RADIUS),
        blurRounds = int(AppConfig.PREF_BLUR_ROUNDS, AppConfig.DEFAULT_BLUR_ROUNDS),
        blurBottomBlobAnimation = bool(AppConfig.PREF_BLUR_BOTTOM_BLOB_ANIM),
        blurBottomRadius = float(AppConfig.PREF_BLUR_BOTTOM_RADIUS, AppConfig.DEFAULT_BLUR_BOTTOM_RADIUS),
        blurBottomAlpha = int(AppConfig.PREF_BLUR_BOTTOM_ALPHA, AppConfig.DEFAULT_BLUR_BOTTOM_ALPHA)
    )

    private fun bool(key: String) = MmkvManager.decodeSettingsBool(key, false)
    private fun int(key: String, default: Int) = MmkvManager.decodeSettingsInt(key, default)
    private fun float(key: String, default: Float) = MmkvManager.decodeSettingsFloat(key, default)
    private fun string(key: String, default: String = "") = MmkvManager.decodeSettingsString(key, default) ?: default
}
